version: '3'
services:
  web:
    image: 497371273566.dkr.ecr.eu-central-1.amazonaws.com/docker-frontend:latest
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:3001"

  api:
    image: 497371273566.dkr.ecr.eu-central-1.amazonaws.com/docker-backend:latest
    ports:
      - "3001:3001"
    environment:
      GITHUB_OAUTH_TOKEN: "/run/secrets/github_oauth_token"
    secrets:
      - github_oauth_token

  mongo:
    image: mongo
    ports:
      - "27017:27017"

secrets:
  github_oauth_token:
    file: ./github_oauth_token.txt  # Lokaler Pfad zur Secret-Datei für Entwicklungs-/Testzwecke

